### ISSUE TITLE
train and inference

### ISSUE THREAD

**Issue by seekingdeep** [yts2020/DBnet_pytorch#1]
@yts19871111 @yts2020 Hi there,
i ran the `DBnet_pytorch.py` script to train, which created a `DBnet_pytorch.pth` file.
Then when i run the `DBnet_pytorch.py` script to inference, i get error:
```
(mmocr) home@home-lnx:~/programs/DBnet_pytorch$ python test.py
Traceback (most recent call last):
  File "test.py", line 443, in <module>
    inference(model, test_loader)
  File "test.py", line 390, in inference
    _, contours, _ = cv2.findContours(pre, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by yts2020** [comment]
这是opencv-python版本的问题，你的版本只有2个返回值，我的版本有3个返回值，我的版本为4.4.0

**Comment by seekingdeep** [comment]
i am still getting the same error after installing opencv 4.4.0
- it's better that you upload the requirements.txt by running `pip freeze > requirements.txt`
- also, it's better that you upload a sample model `DBnet_pytorch.pth` so i can test.

**Comment by yts2020** [comment]
Thank you for your advice！ You can try：
contours, _ = cv2.findContours(pre, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

**Comment by seekingdeep** [comment]
After removing `_,` from `_, contours, _` i can now inference but the issue is that nothing is detected.
- How to train correctly? because when i run training it instantly creates `DBnet_pytorch.pth` and nothing is printed

**Comment by yts2020** [comment]
You need to prepare your own dataset.I used 3000 images as  training set.
